version: '3.7'

services:
  polarislog-frontend:
    build:
      context: ./frontend
      args:
        APP_API_URL: http://localhost:5000
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - polarislog-api

  polarislog-api:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 5000:80
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  postgres_data: