name: React JS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build PolarisLog Frontend
      run: docker build --build-arg APP_API_URL=https://polarislog.eduardoazevedo.dev/api -t carloseduard0/polarislog-frontend ./frontend
    - name: Docker push
      run: docker push carloseduard0/polarislog-frontend